apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-deployment
  labels:
    app: billing-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: {{ .Values.container.billingImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5076
        env:
        - name: KafkaBootstrap
          value: kafka.kafka-ca1:9092
        - name: PostgresOptions__Host
          value: pg-minikube-postgresql.default.svc.cluster.local
        - name: PostgresOptions__Database
          value: billingdb20
        - name: DB_BILLING_USER
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbUser
        - name: DB_BILLING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbPassword