apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Urls": "http://localhost:8000",
      "PostgresOptions": {
        "Host": "pg-minikube-postgresql.default.svc.cluster.local",
        "Port": 5432,
        "Database": "usersdb2",
        "Pooling": true
      }
    }