apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      volumes:
      - name: appsettings-volume
        configMap:
          name: cm
      containers:
      - name: demo
        image: {{ .Values.container.image }}
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: dbUser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: dbPassword