apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: {{ .Values.container.notificationImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5075
        env:
        - name: PostgresOptions__Host
          value: pg-minikube-postgresql.default.svc.cluster.local
        - name: PostgresOptions__Database
          value: notificationdb20
        - name: DB_NOTIFICATION_USER
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbUser
        - name: DB_NOTIFICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbPassword