apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: {{ .Values.container.ordersImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5074
        env:
        - name: KafkaBootstrap
          value: kafka.kafka-ca1:9092
        - name: PostgresOptions__Host
          value: pg-minikube-postgresql.default.svc.cluster.local
        - name: PostgresOptions__Database
          value: ordersdb20
        - name: DB_ORDERS_USER
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbUser
        - name: DB_ORDERS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbPassword