apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: {{ .Values.container.storageImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5072
        env:
        - name: KafkaBootstrap
          value: kafka.kafka-ca1:9092
        - name: PostgresOptions__Host
          value: pg-minikube-postgresql.default.svc.cluster.local
        - name: PostgresOptions__Database
          value: storagedb20
        - name: DB_STORAGE_USER
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbUser
        - name: DB_STORAGE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: dbPassword