container:
  usersImage: f210/user-service:v20
  authImage: f210/authentication-service:v20
  gatewayImage: f210/gateway-service:v20
  billingImage: f210/billing-service:v20
  storageImage: f210/storage-service:v20
  deliveryImage: f210/deliveries-service:v20
  notificationImage: f210/notification-service:v20
  ordersImage: f210/orders-service:v20

replicaCount: 1